project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    left: 
      - home.qmd
    right:
      - icon: github
        href: https://github.com/SilentStorm2k
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto
